"""
Generate google docs from a spreadsheet generated by Google forms
"""

from pydrive.auth import GoogleAuth # pip install pydrive
from pydrive.drive import GoogleDrive
import pandas as pd
from tqdm import tqdm
from string_funcs import *

tqdm.pandas()


# Google Docs API Authentication
# Need `client_secrets.json` (authentication file from Google APIs)
# in directory. See pyDrive documentation
gauth = GoogleAuth()
gauth.LocalWebserverAuth() # Creates local webserver and auto handles authentication.

drive = GoogleDrive(gauth)


def createFile(title, content):
    """
    Create google doc with title = title and content = content
    Doc has "Anyone with link can edit" authorization. Returns link of doc
    """
    f = drive.CreateFile({'title' : title})
    f.SetContentString(content)
    f.Upload({'convert' : True})
    f.InsertPermission({
                'type': 'anyone',
                'value': 'anyone',
                'role': 'writer',
                'withLink' : True})
    return f.metadata['alternateLink'] # returns link


def createFromFile(filename):
    """
    Read filename (CSV) file, create abstracts, returns dataframe with link to abstract pages
    """

    # needs a csv file of information, see pandas documentation
    df = pd.read_csv(filename)

    url_lst = []
    for i, r in tqdm(df.iterrows()):
        # write title and content
        title = '{}___{}'.format(i, filter_body(r['Abstract Title']))
        content = filter_body(r['Abstract Body'])

        # upload file, save url to url_lst
        url_lst.append(createFile(title, content))

    df['doc_url'] = pd.Series(url_lst)

    # returns spreadsheet with url row
    return df.reset_index()



